moneypenny:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "base-lsp.lsst.codes"

  orders:
    commission:
      - name: initcommission
        image: lsstsqre/inituserhome
        securityContext:
          runAsUser: 0
          runAsNonRootUser: false
        volumeMounts:
          - mountPath: /homedirs
            name: homedirs
    volumes:
      - name: homedirs
        nfs:
          server: ddn-nfs.ls.lsst.org
          path: /lsstdata/user/staff/jhome

pull-secret:
  enabled: true
  path: "secret/k8s_operator/base-lsp.lsst.codes/pull-secret"
