moneypenny:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "data-dev.lsst.cloud"

  orders:
    commission:
      - name: initcommission
        image: lsstsqre/inituserhome
        securityContext:
          runAsUser: 0
          runAsNonRootUser: false
        volumeMounts:
          - mountPath: /homedirs
            name: homedirs
    volumes:
      - name: homedirs
        nfs:
          server: 10.87.86.26
          path: /share1/home

pull-secret:
  enabled: true
  path: "secret/k8s_operator/data-dev.lsst.cloud/pull-secret"
