moneypenny:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "rsp.lsst.ac.uk"

  orders:
    commission:
      - name: initcommission
        image: lsstsqre/inituserhome
        securityContext:
          runAsUser: 0
          runAsNonRootUser: false
        volumeMounts:
          - mountPath: /homedirs
            name: homedirs

pull-secret:
  enabled: true
  path: "secret/k8s_operator/roe/pull-secret"
