moneypenny:

  imagePullSecrets:
    - name: "pull-secret"

  ingress:
    enabled: true
    host: "rubin-data-dev.slac.stanford.edu"

  orders: 
    commission:
      - name: initcommission
        image: lsstsqre/inituserhome
        securityContext:
          runAsUser: 0
          runAsNonRootUser: false
        volumeMounts:
        - mountPath: /homedirs
          name: homedirs
    volumes:
      - name: homedirs
        local:
          path: /home

pull-secret:
  enabled: true
  path: "secret/usdf-staffrsp-dev/pull-secret"
