moneypenny:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "data.lsst.cloud"

  orders:
    commission:
      - name: initcommission
        image: lsstsqre/inituserhome
        securityContext:
          runAsUser: 0
          runAsNonRootUser: false
        volumeMounts:
          - mountPath: /homedirs
            name: homedirs
    volumes:
      - name: homedirs
        nfs:
          server: 10.13.105.122
          path: /share1/home

pull-secret:
  enabled: true
  path: "secret/k8s_operator/data.lsst.cloud/pull-secret"
