cadc-tap:
  fullnameOverride: "cadc-tap"

  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "rsp.lsst.ac.uk"
  vaultSecretsPath: "secret/k8s_operator/roe/tap"

pull-secret:
  enabled: true
  path: "secret/k8s_operator/roe/pull-secret"
