cadc-tap-postgres:
  fullnameOverride: "obstap"

  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "data.lsst.cloud"
  vaultSecretsPath: "secret/k8s_operator/data.lsst.cloud/tap"

  config:
    gcsBucket: "async-results.lsst.codes"
    gcsBucketUrl: "http://async-results.lsst.codes"

pull-secret:
  enabled: true
  path: "secret/k8s_operator/data.lsst.cloud/pull-secret"
