environment: int
fqdn: lsst-lsp-int.ncsa.illinois.edu
vault_path_prefix: secret/k8s_operator/lsst-lsp-int.lsst.codes

alert_stream_broker:
  enabled: false
cachemachine:
  enabled: true
cert_issuer:
  enabled: false
cert_manager:
  enabled: false
chronograf:
  enabled: false
datalinker:
  enabled: true
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
influxdb:
  enabled: false
kapacitor:
  enabled: false
mobu:
  enabled: true
moneypenny:
  enabled: true
ingress_nginx:
  enabled: false
noteburst:
  enabled: false
nublado2:
  enabled: true
obstap:
  enabled: true
plot_navigator:
  enabled: false
portal:
  enabled: true
postgres:
  enabled: true
semaphore:
  enabled: false
squareone:
  enabled: true
squash_api:
  enabled: false
strimzi:
  enabled: false
strimzi_registry_operator:
  enabled: false
tap:
  enabled: true
tap_schema:
  enabled: true
vault_secrets_operator:
  enabled: true
vo_cutouts:
  enabled: false
