environment: squash-sandbox
fqdn: squash-sandbox.lsst.codes
vault_path_prefix: secret/k8s_operator/squash-sandbox.lsst.codes

alert_stream_broker:
  enabled: false
cachemachine:
  enabled: false
cert_manager:
  enabled: true
datalinker:
  enabled: false
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
mobu:
  enabled: false
moneypenny:
  enabled: false
ingress_nginx:
  enabled: true
narrativelog:
  enabled: false
noteburst:
  enabled: false
nublado2:
  enabled: false
obstap:
  enabled: false
plot_navigator:
  enabled: false
portal:
  enabled: false
postgres:
  enabled: true
sasquatch:
  enabled: false
production_tools:
  enabled: false
semaphore:
  enabled: false
squareone:
  enabled: false
squash_api:
  enabled: true
strimzi:
  enabled: false
strimzi_registry_operator:
  enabled: false
tap:
  enabled: false
tap_schema:
  enabled: false
telegraf:
  enabled: false
telegraf-ds:
  enabled: false
times_square:
  enabled: false
vault_secrets_operator:
  enabled: true
vo_cutouts:
  enabled: false
