environment: summit
fqdn: summit-lsp.lsst.codes
vault_path_prefix: secret/k8s_operator/summit-lsp.lsst.codes

alert_stream_broker:
  enabled: false
cachemachine:
  enabled: true
cert_issuer:
  enabled: true
cert_manager:
  enabled: true
chronograf:
  enabled: false
datalinker:
  enabled: false
exposurelog:
  enabled: true
gafaelfawr:
  enabled: true
influxdb:
  enabled: false
kapacitor:
  enabled: false
mobu:
  enabled: false
moneypenny:
  enabled: true
ingress_nginx:
  enabled: true
noteburst:
  enabled: false
nublado2:
  enabled: true
obstap:
  enabled: false
plot_navigator:
  enabled: false
portal:
  enabled: true
postgres:
  enabled: true
semaphore:
  enabled: false
squareone:
  enabled: true
squash_api:
  enabled: false
strimzi:
  enabled: false
strimzi_registry_operator:
  enabled: false
tap:
  enabled: false
tap_schema:
  enabled: false
vault_secrets_operator:
  enabled: true
vo_cutouts:
  enabled: false
