environment: idfint
fqdn: data-int.lsst.cloud
vault_path_prefix: secret/k8s_operator/data-int.lsst.cloud

alert_stream_broker:
  enabled: true
cachemachine:
  enabled: true
cert_issuer:
  enabled: true
cert_manager:
  enabled: true
chronograf:
  enabled: false
datalinker:
  enabled: true
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
influxdb:
  enabled: false
kapacitor:
  enabled: false
mobu:
  enabled: true
moneypenny:
  enabled: true
ingress_nginx:
  enabled: true
noteburst:
  enabled: false
nublado2:
  enabled: true
obstap:
  enabled: true
plot_navigator:
  enabled: true
portal:
  enabled: true
postgres:
  enabled: true
semaphore:
  enabled: true
squareone:
  enabled: true
squash_api:
  enabled: false
strimzi:
  enabled: true
strimzi_registry_operator:
  enabled: true
tap:
  enabled: true
tap_schema:
  enabled: true
vault_secrets_operator:
  enabled: true
vo_cutouts:
  enabled: true
