alert_stream_broker:
  enabled: false
cachemachine:
  enabled: false
cert_issuer:
  enabled: false
cert_manager:
  enabled: false
chronograf:
  enabled: false
datalinker:
  enabled: false
exposurelog:
  enabled: false
gafaelfawr:
  enabled: false
influxdb:
  enabled: false
ingress_nginx:
  enabled: false
kapacitor:
  enabled: false
mobu:
  enabled: false
moneypenny:
  enabled: false
noteburst:
  enabled: false
nublado2:
  enabled: false
obstap:
  enabled: false
plot_navigator:
  enabled: false
portal:
  enabled: false
postgres:
  enabled: false
semaphore:
  enabled: false
sherlock:
  enabled: false
squareone:
  enabled: false
squash_api:
  enabled: false
strimzi:
  enabled: false
strimzi_registry_operator:
  enabled: false
tap:
  enabled: false
tap_schema:
  enabled: false
vault_secrets_operator:
  enabled: false
vo_cutouts:
  enabled: false

repoURL: https://github.com/lsst-sqre/phalanx.git
revision: HEAD
onepassword_uuid: "dg5afgiadsffeklfr6jykqymeu"
