apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Values.cluster.name }}-connect
  labels:
    strimzi.io/cluster: {{ .Values.cluster.name }}
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: group
          name: {{ .Values.cluster.name }}-connect
        operation: Read
      - resource:
          type: group
          name: connect-influxdb-sink
          patternType: literal
        operation: All
      - resource:
          type: topic
          name: "*"
          patternType: literal
        type: allow
        host: "*"
        operation: All
  quotas:
    producerByteRate: 1073741824
    consumerByteRate: 1073741824
    requestPercentage: 90
    controllerMutationRate: 1000

