apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .Values.registry.schemaTopic }}
  labels:
    strimzi.io/cluster: {{ .Values.cluster.name }}
spec:
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: compact
