apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: ts-salkafka
  labels:
    strimzi.io/cluster: {{ .Values.cluster.name }}
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: sasquatch
          key: ts-salkafka-password
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "lsst.sal"
          patternType: prefix
        type: allow
        host: "*"
        operation: All
  quotas:
    producerByteRate: 1073741824
    consumerByteRate: 1073741824
    requestPercentage: 90
    controllerMutationRate: 1000

