apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: ts-salkafka
  labels:
    strimzi.io/cluster: {{ .Values.cluster.name }}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "lsst.sal.*"
          patternType: literal
        type: allow
        host: "*"
        operation: All
