{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with .Values.ingress.anonymousAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "cachemachine.fullname" . }}-anonymous
  labels:
    {{- include "cachemachine.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ required "ingress.host must be set" .Values.ingress.host | quote }}
      http:
        paths:
          - path: "/cachemachine/.*/available"
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ template "cachemachine.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          - path: "/cachemachine/.*/desired"
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ template "cachemachine.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
