replicaCount: 2

# Use the CSI storage class so that we can use snapshots.
redis:
  persistence:
    storageClass: "wekafs--sdf-k8s01"

config:
  databaseUrl: "postgresql://gafaelfawr@postgres.postgres/gafaelfawr"

  oidc:
    clientId: rubin-usdf-rsp
    audience: "rubin-usdf-rsp"
    loginUrl: "https://dex.slac.stanford.edu/auth"
    tokenUrl: "https://dex.slac.stanford.edu/token"
    issuer: "https://dex.slac.stanford.edu"
    scopes:
    - "openid"
    - "email"
    - "groups"
    - "profile"
    usernameClaim: "name"

  ldap:
    url: ldaps://ldap-unix.slac.stanford.edu:636
    groupBaseDn: ou=Group,dc=slac,dc=stanford,dc=edu
    groupObjectClass: posixGroup
    groupMemberAttr: memberUid    
    userBaseDn: ou=Accounts,dc=slac,dc=stanford,dc=edu
    userSearchAttr: uid
    uidAttr: uidNumber


  # Allow access by GitHub team.
  groupMapping:
    "admin:users":
      - "rubinmgr"
      - "unix-admin" 
    "exec:admin":
      - "rubinmgr"
      - "unix-admin"
    "exec:notebook":
      - "lsst"
      - lsst-ccs
      - rubin_users
      - rubin_admin_datasets
      - rubin_admin_repos
      - "unix-admin"
    "exec:portal":
      - "lsst"
      - lsst-ccs
      - rubin_users
      - rubin_admin_datasets
      - rubin_admin_repos
      - "unix-admin"
    "exec:user":
      - "lsst"
      - lsst-ccs
      - rubin_users
      - rubin_admin_datasets
      - rubin_admin_repos
      - "unix-admin"
    "read:tap":
      - "lsst"
      - lsst-ccs
      - rubin_users
      - rubin_admin_datasets
      - rubin_admin_repos
      - "unix-admin"

  initialAdmins:
    - "afausti"
    - "athornton"
    - "cbanek"
    - "frossie"
    - "jonathansick"
    - "rra"
    - "simonkrughoff"
    - "ytl"
    - "ppascual"

  errorFooter: |
    To report problems or ask for help, please open an issue in the
    <a href="https://github.com/rubin-dp0/Support/issues">GitHub
    rubin-dp0/Support project</a>.

cloudsql:
  enabled: false

