replicaCount: 2

# Use an existing, manually-managed PVC for Redis.
redis:
  persistence:
    volumeClaimName: "auth-redis-volume-claim"

config:
  databaseUrl: "postgresql://gafaelfawr@postgres.postgres/gafaelfawr"

  # IP range used by the cluster, used to determine the true client IP for
  # logging.
  proxies:
    - "41.142.182.128/26"

  # Support OpenID Connect clients like Chronograf.
  oidcServer:
    enabled: true

  # Use CILogon authentication.
  cilogon:
    clientId: "cilogon:/client_id/7ae419868b97e81644ced9886ffbcec"
    redirectUrl: "https://lsst-lsp-stable.ncsa.illinois.edu/oauth2/callback"
    loginParams:
      skin: "LSST"

  # Use NCSA groups to determine token scopes.
  groupMapping:
    "admin:provision": ["lsst_int_lsp_admin"]
    "exec:admin": ["lsst_int_lsp_admin"]
    "exec:notebook": ["lsst_int_lspdev"]
    "exec:portal": ["lsst_int_lspdev"]
    "read:tap": ["lsst_int_lspdev"]

  initialAdmins:
    - "afausti"
    - "athornto"
    - "cbanek"
    - "frossie"
    - "jsick"
    - "krughoff"
    - "rra"
