# Use the CSI storage class so that we can use snapshots.
redis:
  persistence:
    storageClass: "standard-rwo"

config:
  databaseUrl: "postgresql://gafaelfawr@localhost/gafaelfawr"
  loglevel: "DEBUG"
  slackAlerts: true

  # Support OpenID Connect clients like Chronograf.
  oidcServer:
    enabled: true

  cilogon:
    clientId: "cilogon:/client_id/46f9ae932fd30e9fb1b246972a3c0720"
    enrollmentUrl: "https://registry-test.lsst.codes/registry/co_petitions/start/coef:6"
    test: true
    usernameClaim: "username"

  firestore:
    project: "rsp-firestore-dev-31c4"

  ldap:
    url: "ldaps://ldap-test.cilogon.org"
    userDn: "uid=readonly_user,ou=system,o=LSST,o=CO,dc=lsst,dc=org"
    groupBaseDn: "ou=groups,o=LSST,o=CO,dc=lsst,dc=org"
    groupObjectClass: "eduMember"
    groupMemberAttr: "hasMember"
    userBaseDn: "ou=people,o=LSST,o=CO,dc=lsst,dc=org"
    userSearchAttr: "voPersonApplicationUID"
    addUserGroup: true

  groupMapping:
    "admin:provision":
      - "g_science-platform-idf-dev"
    "exec:admin":
      - "g_science-platform-idf-dev"
    "exec:notebook":
      - "g_science-platform-idf-dev"
    "exec:portal":
      - "g_science-platform-idf-dev"
    "read:image":
      - "g_science-platform-idf-dev"
    "read:tap":
      - "g_science-platform-idf-dev"

  initialAdmins:
    - "afausti"
    - "adam"
    - "cbanek"
    - "frossie"
    - "jsick"
    - "rra"
    - "simonkrughoff"

cloudsql:
  enabled: true
  instanceConnectionName: "science-platform-dev-7696:us-central1:science-platform-dev-e9e11de2"
  serviceAccount: "gafaelfawr@science-platform-dev-7696.iam.gserviceaccount.com"
