strimzi-kafka:
  kafka:
    storage:
      storageClassName: rook-ceph-block
  zookeeper:
    storage:
      storageClassName: rook-ceph-block

influxdb:
  persistence:
    storageClass: rook-ceph-block
  ingress:
    enabled: true
    tls: true
    secretName: tls-certs
    hostname: influxdb-tucson-teststand-efd.lsst.codes
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/proxy-body-size: "0m"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Path /;
    path: /


kafka-connect-manager:
  influxdbSink:
    influxdb-sink:
      enabled: true
      connectInfluxErrorPolicy: NOOP
      tasksMax: 10

kafdrop:
  ingress:
    enabled: true
    hostname: tucson-teststand.lsst.codes

chronograf:
  persistence:
    storageClass: rook-ceph-block
  ingress:
    enabled: true
    hostname: tucson-teststand.lsst.codes
  env:
    GENERIC_NAME: "OIDC"
    GENERIC_AUTH_URL: https://tucson-teststand.lsst.codes/auth/openid/login
    GENERIC_TOKEN_URL: https://tucson-teststand.lsst.codes/auth/openid/token
    USE_ID_TOKEN: 1
    JWKS_URL: https://tucson-teststand.lsst.codes/.well-known/jwks.json
    GENERIC_API_URL: https://tucson-teststand.lsst.codes/auth/userinfo
    GENERIC_SCOPES: openid
    GENERIC_API_KEY: sub
    PUBLIC_URL: https://tucson-teststand.lsst.codes
    STATUS_FEED_URL: https://raw.githubusercontent.com/lsst-sqre/rsp_broadcast/main/jsonfeeds/tucson-teststand.json

kapacitor:
  persistence:
    storageClass: rook-ceph-block
