strimzi-kafka:
  kafka:
    externalListener:
      tls:
        enabled: true
      bootstrap:
        loadBalancerIP: ""
        host: sasquatch-int-kafka-bootstrap.lsst.cloud

      brokers:
        - loadBalancerIP: ""
          host: sasquatch-int-kafka-0.lsst.cloud
        - loadBalancerIP: ""
          host: sasquatch-int-kafka-1.lsst.cloud
        - loadBalancerIP: ""
          host: sasquatch-int-kafka-2.lsst.cloud

influxdb:
  ingress:
    enabled: true
    hostname: data-int.lsst.cloud

kafka-connect-manager:
  influxdbSink:
    influxdb-sink:
      enabled: true
      tasksMax: 10

kafdrop:
  ingress:
    enabled: true
    hostname: data-int.lsst.cloud

chronograf:
  ingress:
    enabled: true
    hostname: data-int.lsst.cloud

  env:
    GENERIC_NAME: "OIDC"
    GENERIC_AUTH_URL: https://data-int.lsst.cloud/auth/openid/login
    GENERIC_TOKEN_URL: https://data-int.lsst.cloud/auth/openid/token
    USE_ID_TOKEN: 1
    JWKS_URL: https://data-int.lsst.cloud/.well-known/jwks.json
    GENERIC_API_URL: https://data-int.lsst.cloud/auth/userinfo
    GENERIC_SCOPES: openid
    GENERIC_API_KEY: sub
    PUBLIC_URL: https://data-int.lsst.cloud/
    STATUS_FEED_URL: https://raw.githubusercontent.com/lsst-sqre/rsp_broadcast/main/jsonfeeds/idfint.json
