strimzi-kafka: {}

influxdb:
  ingress:
    enabled: true
    hostname: data-dev.lsst.cloud

kafka-connect-manager:
  influxdbSink:
    influxdb-sink:
      enabled: true
      tasksMax: 10

kafdrop:
  ingress:
    enabled: true
    hostname: data-dev.lsst.cloud

chronograf:
  ingress:
    enabled: true
    hostname: data-dev.lsst.cloud

  env:
    GENERIC_NAME: "OIDC"
    GENERIC_AUTH_URL: https://data-dev.lsst.cloud/auth/openid/login
    GENERIC_TOKEN_URL: https://data-dev.lsst.cloud/auth/openid/token
    USE_ID_TOKEN: 1
    JWKS_URL: https://data-dev.lsst.cloud/.well-known/jwks.json
    GENERIC_API_URL: https://data-dev.lsst.cloud/auth/userinfo
    GENERIC_SCOPES: openid
    GENERIC_API_KEY: sub
    PUBLIC_URL: https://data-dev.lsst.cloud/
    STATUS_FEED_URL: https://raw.githubusercontent.com/lsst-sqre/rsp_broadcast/main/jsonfeeds/idfdev.json
