config:
  # There is currently no working Butler in data-dev, so this configuration
  # won't work.  Leaving it here anyway since it has the correct configuration
  # otherwise should we later get a Butler for that environment.
  butlerRepository: "TBD"
  databaseUrl: "postgresql://vo-cutouts@localhost/vo-cutouts"
  gcsBucketUrl: "s3://rubin-cutouts-dev-us-central1-output/"

cloudsql:
  enabled: true
  instanceConnectionName: "science-platform-dev-7696:us-central1:science-platform-dev-e9e11de2"
  serviceAccount: "vo-cutouts@science-platform-dev-7696.iam.gserviceaccount.com"
