{{- if .Values.sherlock.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: sherlock
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sherlock
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sherlock
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/sherlock
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.revision }}
    helm:
      valueFiles:
        - values-{{ .Values.environment }}.yaml
{{- end -}}
