
{{- if .Values.telegraf.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: telegraf
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: telegraf
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/telegraf
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.revision }}
    helm:
      parameters:
        - name: "global.enabled_services"
          value: {{ include "enabled_services" . | quote }}
        - name: "global.host"
          value: {{ .Values.fqdn | quote }}
        - name: "global.vaultSecretsPath"
          value: {{ .Values.vault_path_prefix | quote }}
      valueFiles:
        - values.yaml
        - values-{{ .Values.environment }}.yaml
{{- end -}}

