sherlock:
  ingress:
    host: "data.lsst.cloud"

  resources:
    requests:
      cpu: 2.0
      memory: "2G"
    limits:
      cpu: 4.0
      memory: "4G"

  publish_url: "https://status.lsst.codes/api/data"
  vaultSecretsPath: "secret/k8s_operator/data.lsst.cloud/sherlock"
