config:
  siteName: "Rubin Science Platform @ data-int"
  semaphoreUrl: "https://data-int.lsst.cloud/semaphore"

pull-secret:
  enabled: true
  path: secret/k8s_operator/data-int.lsst.cloud/pull-secret
