image:
  pullPolicy: Always

config:
  siteName: "Rubin Science Platform @ data-dev"
  semaphoreUrl: "https://data-dev.lsst.cloud/semaphore"

pull-secret:
  enabled: true
  path: secret/k8s_operator/data-dev.lsst.cloud/pull-secret
