apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ template "vo-cutouts.fullname" . }}-secret
  labels:
    {{- include "vo-cutouts.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/vo-cutouts"
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "pull-secret"
  labels:
    {{- include "vo-cutouts.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/pull-secret"
  type: "kubernetes.io/dockerconfigjson"
