# Global parameters will be set by parameters injected via the Argo CD
# Application resource and should not be set in the individual environment
# values files.
global:
  # -- Base URL for the environment
  # @default -- Set by times-square Argo CD Application
  baseUrl: ""

  # -- Host name for ingress
  # @default -- Set by times-square Argo CD Application
  host: ""

  # -- Base path for Vault secrets
  # @default -- Set by times-square Argo CD Application
  vaultSecretsPathPrefix: ""

times-square:

  fullnameOverride: times-square

  image:
    tag: "tickets-DM-34458"

    pullPolicy: "IfNotPresent"

  config:
    # -- URL for Redis html / noteburst job cache database
    # @default -- Points to embedded Redis
    redisUrl: "redis://times-square-redis-master:6379/0"

    # -- URL for Redis arq queue database
    # @default -- Points to embedded Redis
    queueRedisUrl: "redis://times-square-redis-master:6379/1"

times-square-ui:

  fullnameOverride: times-square-ui

  image:
    tag: "0.2.0"

    pullPolicy: "IfNotPresent"

redis:
  fullnameOverride: times-square-redis

  auth:
    enabled: false
