apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "times-square-ui.fullname" . }}
  labels:
    {{- include "times-square-ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "times-square-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "times-square-ui.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "{{ .Values.ingress.path }}/"
              port: http
          readinessProbe:
            httpGet:
              path: "{{ .Values.ingress.path }}/"
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: "TS_CONFIG_PATH"
              value: "/etc/times-square/times-square.config.yaml"
          volumeMounts:
            - name: "config"
              mountPath: "/etc/times-square"
            - name: "next-image-cache"
              mountPath: "/app/.next/cache/images"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: "config"
          configMap:
            name: {{ include "times-square-ui.fullname" . }}
        - name: "next-image-cache"
          emptyDir: {}
