ingress-nginx:
  controller:
    service:
      externalTrafficPolicy: null
      type: ClusterIP
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    admissionWebhooks:
      enabled: false
    extraArgs:
      default-ssl-certificate: ingress-nginx/ingress-certificate

vault_certificate:
  enabled: true
