mobu:
  imagePullSecrets:
    - name: "pull-secret"

  ingress:
    host: "red-five.lsst.codes"

  environmentUrl: "https://red-five.lsst.codes"
  vaultSecretsPath: "secret/k8s_operator/red-five.lsst.codes/mobu"

pull-secret:
  enabled: true
  path: "secret/k8s_operator/red-five.lsst.codes/pull-secret"
