cachemachineImagePolicy: "desired"

autostart:
  - name: "python"
    count: 1
    users:
      - username: "systemtest01"
        uidnumber: 74768
    scopes: ["exec:notebook"]
    business: "JupyterPythonLoop"
    options:
      jupyter:
        image_size: "Small"
    restart: true
