autostart:
  - name: "firefighter"
    count: 5
    users:
      - username: "lsptestuser01"
        uidnumber: 60181
      - username: "lsptestuser02"
        uidnumber: 60182
      - username: "lsptestuser03"
        uidnumber: 60183
      - username: "lsptestuser04"
        uidnumber: 60184
      - username: "lsptestuser05"
        uidnumber: 60185
    scopes: ["exec:notebook", "exec:portal", "read:tap"]
    business: "NotebookRunner"
    options:
      repo_url: "https://github.com/lsst-sqre/system-test.git"
      repo_branch: "NCSA-prod"
      max_executions: 1
    restart: true
