mobu:
  imagePullSecrets:
    - name: "pull-secret"

  ingress:
    host: "data-int.lsst.cloud"

  environmentUrl: "https://data-int.lsst.cloud"
  vaultSecretsPath: "secret/k8s_operator/data-int.lsst.cloud/mobu"

  autostart:
    - name: "firefighter"
      count: 1
      users:
        - username: "systemtest01"
          uidnumber: 74768
      scopes: ["exec:notebook", "exec:portal", "read:tap"]
      business: "NotebookRunner"
      options:
        repo_url: "https://github.com/SimonKrughoff/system-test.git"
        repo_branch: "prod"
        max_executions: 1
      restart: true
    - name: "weekly"
      count: 1
      users:
        - username: "systemtest02"
          uidnumber: 74769
      scopes: ["exec:notebook", "exec:portal", "read:tap"]
      business: "NotebookRunner"
      options:
        jupyter:
          image_class: "latest-weekly"
        repo_url: "https://github.com/lsst-sqre/system-test.git"
        repo_branch: "prod"
      restart: true

pull-secret:
  enabled: true
  path: "secret/k8s_operator/data-int.lsst.cloud/pull-secret"
