cachemachineImagePolicy: "desired"

autostart:
  - name: "firefighter"
    count: 1
    users:
      - username: "bot-mobu-recommended"
        uidnumber: 74768
    scopes:
      - "exec:notebook"
      - "exec:portal"
      - "read:image"
      - "read:tap"
    business: "NotebookRunner"
    options:
      repo_url: "https://github.com/SimonKrughoff/system-test.git"
      repo_branch: "prod"
      max_executions: 1
    restart: true
  - name: "weekly"
    count: 1
    users:
      - username: "bot-mobu-weekly"
        uidnumber: 74769
    scopes:
      - "exec:notebook"
      - "exec:portal"
      - "read:image"
      - "read:tap"
    business: "NotebookRunner"
    options:
      jupyter:
        image_class: "latest-weekly"
      repo_url: "https://github.com/lsst-sqre/system-test.git"
      repo_branch: "prod"
    restart: true
  - name: "tap"
    count: 120
    user_spec:
      username_prefix: "bot-mobu-tap"
      uid_start: 74770
    scopes: ["read:tap"]
    business: "TAPQueryRunner"
    restart: true
