apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: {{ template "gafaelfawr.fullname" . }}
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ required "global.host must be set" .Values.global.host | quote }}
      http:
        paths:
          - path: "/auth"
            pathType: Prefix
            backend:
              service:
                name: {{ template "gafaelfawr.fullname" . }}
                port:
                  number: 8080
          - path: "/login"
            pathType: Exact
            backend:
              service:
                name: {{ template "gafaelfawr.fullname" . }}
                port:
                  number: 8080
          - path: "/logout"
            pathType: Exact
            backend:
              service:
                name: {{ template "gafaelfawr.fullname" . }}
                port:
                  number: 8080
          - path: "/oauth2/callback"
            pathType: Exact
            backend:
              service:
                name: {{ template "gafaelfawr.fullname" . }}
                port:
                  number: 8080
          - path: "/.well-known/jwks.json"
            pathType: Exact
            backend:
              service:
                name: {{ template "gafaelfawr.fullname" . }}
                port:
                  number: 8080
          {{- if .Values.config.oidcServer.enabled }}
          - path: "/.well-known/openid-configuration"
            pathType: Exact
            backend:
              service:
                name: {{ template "gafaelfawr.fullname" . }}
                port:
                  number: 8080
          {{- end }}
