apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/auth/tokens/"
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: {{ template "gafaelfawr.fullname" . }}-rewrite
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ required "global.host must be set" .Values.global.host | quote }}
      http:
        paths:
          - path: "/auth/tokens/id/.*"
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ template "gafaelfawr.fullname" . }}
                port:
                  number: 8080
