apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gafaelfawr.fullname" . }}-tokens
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.cloudsql.enabled }}
    iam.gke.io/gcp-service-account: {{ required "cloudsql.serviceAccount must be set to a valid Google service account" .Values.cloudsql.serviceAccount | quote }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gafaelfawr.fullname" . }}-tokens
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "patch", "update"]
  - apiGroups: ["gafaelfawr.lsst.io"]
    resources: ["gafaelfawrservicetokens", "gafaelfawrservicetokens/status"]
    verbs: ["get", "list", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gafaelfawr.fullname" . }}-tokens
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gafaelfawr.fullname" . }}-tokens
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "gafaelfawr.fullname" . }}-tokens
  apiGroup: rbac.authorization.k8s.io
