apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal.fullname" . }}-redis
  labels:
    {{- include "portal.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - protocol: "TCP"
      port: 6379
      targetPort: 6379
  selector:
    {{- include "portal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "redis"
