apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ template "mobu.fullname" . }}-secret
  labels:
    {{- include "mobu.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/mobu"
  type: "Opaque"
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "pull-secret"
  labels:
    {{- include "mobu.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/pull-secret"
  type: "kubernetes.io/dockerconfigjson"
