apiVersion: v2
name: alert-stream-broker
version: "3"
dependencies:
  - name: alert-stream-broker
    version: 2.5.1
    repository: https://lsst-sqre.github.io/charts/

  # The schema registry is bundled together in the same application as the
  # Kafka broker because Strimzi Registry Operator expects everything (the
  # broker, its secrets, its users, and the StrimziSchemaRegistry custom
  # resource) to be in the same namespace.
  - name: alert-stream-schema-registry
    version: 2.1.0
    repository: https://lsst-sqre.github.io/charts/

  # alert-stream-simulator is bundled together with the broker too for a
  # similar reason: the Strimzi EntityOperator can only watch a single
  # namespace, so all of the Secrets associated with KafkaUsers are in this
  # namespace - and the alert-stream-simulator needs those credentials to
  # connect.
  - name: alert-stream-simulator
    version: 1.6.2
    repository: https://lsst-sqre.github.io/charts/

  - name: alert-database
    version: 2.1.0
    repository: https://lsst-sqre.github.io/charts/
