# Uncomment image to enable development builds
# image:
#   pullPolicy: Always
#   tag: tickets-DM-33025

config:
  logLevel: "DEBUG"
  worker:
    workerCount: 1
    identities:
      - uid: 90000
        username: "noteburst90000"
