noteburst:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: "lsst-lsp-stable.ncsa.illinois.edu"
        paths:
          - path: "/noteburst"
            pathType: Prefix
  imagePullSecrets:
    - name: "pull-secret"
  vaultSecretsPath: "secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/noteburst"

pull-secret:
  enabled: true
  path: secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/pull-secret
