# Default values for exposurelog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: lsstsqre/exposurelog
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Application-specific configuration
config:
  # NFS path to butler registry 1 and/or 2.
  # Only specify a non-blank value if reading the registry from an NFS-mounted file.
  # If not blank then mount the specified NFS path as internal volume /volume_1 or /volume_2, respectively.
  nfs_path_1: ""
  nfs_path_2: ""

  # Name of the NFS server that exports nfs_path_1 or nfs_path_2, respectively.
  # Specify a non-blank value if and only if the corresponding nfs_path_1/2 is not blank.
  nfs_server_1: ""
  nfs_server_2: ""

  # URIs for butler registry 1 (required) and 2 (optional). Format:
  # * For a volume mounted using `nfs_path_1` or `nfs_path_2` (see above):
  #   An absolute path starting with `/volume_1/` or `/volume_2/`.
  # * For a network URI: see the daf_butler documentation.
  # * For a sandbox deployment: specify `LSSTCam` for butler_uri_1 and `LATISS` for butler_uri_2.
  butler_uri_1: ""
  butler_uri_2: ""

  # Site ID; a non-empty string of up to 16 characters.
  # This should be different for each non-sandbox deployment.
  # Sandboxes should use `test`.
  site_id: ""

# Site-specific values files should specify:
#
# ingress:
#   enabled: true
#   host: ...
#
# vault-path: secret/k8s_operator/.../postgres
#
# pull-secret:
#   enabled: true
#   path: secret/k8s_operator/.../pull-secret

# This is needed for the CI job to run
ingress:
  enabled: false

imagePullSecrets:
  - name: pull-secret

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
