cachemachine:
  imagePullSecrets:
    - name: "cachemachine-secret"

  ingress:
    enabled: true
    host: "summit-lsp.lsst.codes"

  vaultSecretsPath: "secret/k8s_operator/summit-lsp.lsst.codes/pull-secret"

  autostart:
    jupyter: |
      {
        "name": "jupyter",
        "labels": {
            "jupyterlab": "ok"
        },
        "repomen": [
          {
            "type": "RubinRepoMan",
            "registry_url": "registry.hub.docker.com",
            "repo": "lsstts/sal-sciplat-lab",
            "recommended_tag": "recommended",
            "num_releases": 0,
            "num_weeklies": 3,
            "num_dailies": 2,
            "cycle": 23,
            "alias_tags": [
                "latest",
                "latest_daily",
                "latest_weekly"
            ]
          }
        ]
      }
