firefly:
  pull_secret: 'pull-secret'

  ingress:
    host: 'lsst-nts-k8s.ncsa.illinois.edu'
    annotations:
      nginx.ingress.kubernetes.io/auth-method: GET
      nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Uid, X-Auth-Request-Token
      nginx.ingress.kubernetes.io/auth-signin: "https://lsst-nts-k8s.ncsa.illinois.edu/login"
      nginx.ingress.kubernetes.io/auth-url: "https://lsst-nts-k8s.ncsa.illinois.edu/auth?scope=exec:portal&delegate_to=portal&delegate_scope=read:tap"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Path /portal/app;

  secrets:
    enabled: false

  vault_secrets:
    enabled: true
    path: 'secret/k8s_operator/lsst-nts-k8s.ncsa.illinois.edu/portal'

  redis:
    resources:
      limits:
        memory: 20Mi

  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: portal

  resources:
    limits:
      memory: 24Gi

  volumes:
    firefly_shared_workarea:
      emptyDir: {}
    firefly_config:
      emptyDir: {}

pull-secret:
  enabled: true
  path: secret/k8s_operator/lsst-nts-k8s.ncsa.illinois.edu/pull-secret
