replicaCount: 2

config:
  volumes:
    workareaHostPath: "/sui/firefly/workarea"
    configHostPath: "/sui/firefly/config"

nodeSelector:
  environment: "portal-stable"

tolerations:
  - effect: "NoSchedule"
    key: "dedicated"
    operator: "Equal"
    value: "portal"

resources:
  limits:
    memory: "24Gi"

securityContext:
  runAsUser: 101
  runAsGroup: 102
