firefly:
  pull_secret: 'pull-secret'

  ingress:
    host: "minikube.lsst.codes"
    annotations:
      nginx.ingress.kubernetes.io/auth-method: GET
      nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Uid, X-Auth-Request-Token
      nginx.ingress.kubernetes.io/auth-signin: "https://minikube.lsst.codes/login"
      nginx.ingress.kubernetes.io/auth-url: "http://gafaelfawr.gafaelfawr.svc.cluster.local:8080/auth?scope=exec:portal&delegate_to=portal&delegate_scope=read:tap"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Path /portal/app;

  resources:
    limits:
      cpu: 0.3
      memory: 2Gi

  secrets:
    enabled: false

  vault_secrets:
    enabled: true
    path: secret/k8s_operator/minikube.lsst.codes/portal

  redis:
    resources:
      limits:
        memory: 20Mi

pull-secret:
  enabled: true
  path: secret/k8s_operator/minikube.lsst.codes/pull-secret
