apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ template "cadc-tap.fullname" . }}-secret
  labels:
    {{- include "cadc-tap.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/tap"
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
  labels:
    {{- include "cadc-tap.labels" . | nindent 4 }}
spec:
  path: "{{- .Values.global.vaultSecretsPath }}/pull-secret"
  type: kubernetes.io/dockerconfigjson
