kind: Service
apiVersion: v1
metadata:
  name: {{ template "cadc-tap-postgres.fullname" . }}
  labels:
    {{- include "cadc-tap-postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  selector:
    {{- include "cadc-tap-postgres.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "server"
