apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "cadc-tap-postgres.fullname" . }}-authenticated
  labels:
    {{- include "cadc-tap-postgres.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-Uid, X-Auth-Request-Token"
    nginx.ingress.kubernetes.io/auth-signin: "{{ .Values.global.baseUrl }}/login"
    nginx.ingress.kubernetes.io/auth-url: "{{ .Values.global.baseUrl }}/auth?{{ .Values.ingress.gafaelfawrAuthQuery }}"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $auth_token $upstream_http_x_auth_request_token;
      proxy_set_header Authorization "Bearer $auth_token";
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
    nginx.ingress.kubernetes.io/rewrite-target: "/tap/$2"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "http://$host/tap/"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://$host/api/obstap/"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with .Values.ingress.authenticatedAnnotations }}
    {{ toYaml . | indent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ required "global.host must be set" .Values.global.host | quote }}
      http:
        paths:
          - path: "/api/obstap(/|$)(.*)"
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ template "cadc-tap-postgres.fullname" . }}
                port:
                  number: 80
