apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cadc-tap-postgres.fullname" . }}-tap-db
  labels:
    {{- include "cadc-tap-postgres.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cadc-tap-postgres.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "tap-db"
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cadc-tap-postgres.labels" . | nindent 8 }}
        app.kubernetes.io/component: "tap-db"
    spec:
      imagePullSecrets:
        - name: "pull-secret"
      automountServiceAccountToken: false
      containers:
        - name: "tap-db"
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.imagePullPolicy | quote }}
          ports:
            - containerPort: 5432
          {{- with .Values.db.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.db.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
