apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cadc-tap-postgres.fullname" . }}
  labels:
    {{- include "cadc-tap-postgres.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cadc-tap-postgres.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "server"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cadc-tap-postgres.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "server"
    spec:
      imagePullSecrets:
        - name: "pull-secret"
      automountServiceAccountToken: false
      containers:
        - name: "tap-server"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          env:
            - name: "CATALINA_OPTS"
              value: >-
                -Dtap.username=tap_schema
                -Dtap.password=pw-tapschema
                -Dtap.url=jdbc:postgresql://{{ template "cadc-tap-postgres.fullname" . }}-tap-db:5432/tap_schema
                -Dtap.maxActive=1
                -Dca.nrc.cadc.reg.client.RegistryClient.local=true
                -Duws.username=postgres
                -Duws.maxActive=2
                -Duws.jdbc.driverClassName=org.postgresql.Driver
                -Duws.url=jdbc:postgresql://{{ template "cadc-tap-postgres.fullname" . }}-uws-db/
                -Dgcs_bucket={{ .Values.config.gcsBucket }}
                -Dgcs_bucket_url={{ .Values.config.gcsBucketUrl }}
                -Dca.nrc.cadc.util.PropertiesReader.dir=/etc/creds/
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/etc/creds/google_creds.json"
          ports:
            - containerPort: 8080
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: "google-creds"
              mountPath: "/etc/creds"
              readOnly: true
            - name: "tmp"
              mountPath: "/tmp"
      volumes:
        - name: "google-creds"
          secret:
            secretName: {{ template "cadc-tap-postgres.fullname" . }}-secret
        - name: "tmp"
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
