kind: Service
apiVersion: v1
metadata:
  name: {{ template "cadc-tap-postgres.fullname" . }}-uws-db
  labels:
    {{- include "cadc-tap-postgres.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: "TCP"
      port: 5432
      targetPort: 5432
  selector:
    {{- include "cadc-tap-postgres.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "uws-db"
