apiVersion: v2
name: nublado2
version: 1.1.0
appVersion: "2.1.0"
description: Nublado2 JupyterHub installation
home: https://github.com/lsst-sqre/nublado2
maintainers:
  - name: cbanek
sources:
  - https://github.com/lsst-sqre/nublado2
# Match the jupyterhub Helm chart for kubeVersion
kubeVersion: ">=1.20.0-0"
dependencies:
  - name: jupyterhub
    # Change when there's an asyncio z2jh officially released
    version: "1.1.3-n410.hd8ae7348"
    repository: https://jupyterhub.github.io/helm-chart/
  - name: pull-secret
    version: 0.1.2
    repository: https://lsst-sqre.github.io/charts/
