nublado2:
  jupyterhub:
    debug:
      enabled: true
    hub:
      resources:
        requests:
          cpu: "1"
          memory: 3Gi
    ingress:
      hosts: ["data-int.lsst.cloud"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://data-int.lsst.cloud/login"

  config:
    base_url: "https://data-int.lsst.cloud"
    butler_secret_path: "secret/k8s_operator/data-int.lsst.cloud/butler-secret"
    lab_environment:
      PGPASSFILE: "/opt/lsst/software/jupyterlab/butler-secret/postgres-credentials.txt"
      AWS_SHARED_CREDENTIALS_FILE: "/opt/lsst/software/jupyterlab/butler-secret/aws-credentials.ini"
      S3_ENDPOINT_URL: "https://storage.googleapis.com"
      # technical debt: for needed for DP0 because deployment branch is not parametrized
      AUTO_REPO_URLS: https://github.com/SimonKrughoff/notebook-demo
    volumes:
      - name: home
        nfs:
          path: /share1/home
          server: 10.22.240.130
      - name: project
        nfs:
          path: /share1/project
          server: 10.22.240.130
      - name: scratch
        nfs:
          path: /share1/scratch
          server: 10.22.240.130
    volume_mounts:
      - name: home
        mountPath: /home
      - name: project
        mountPath: /project
      - name: scratch
        mountPath: /scratch

  vault_secret_path: "secret/k8s_operator/data-int.lsst.cloud/nublado2"
