nublado2:
  jupyterhub:
    hub:
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
    ingress:
      hosts: ["data-dev.lsst.cloud"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://data-dev.lsst.cloud/login"

  config:
    base_url: "https://data-dev.lsst.cloud"
    butler_secret_path: "secret/k8s_operator/data-dev.lsst.cloud/butler-secret"
    pull_secret_path: "secret/k8s_operator/data-dev.lsst.cloud/pull-secret"
    lab_environment:
      PGPASSFILE: "/opt/lsst/software/jupyterlab/butler-secret/postgres-credentials.txt"
      AWS_SHARED_CREDENTIALS_FILE: "/opt/lsst/software/jupyterlab/butler-secret/aws-credentials.ini"
      S3_ENDPOINT_URL: "https://storage.googleapis.com"
      AUTO_REPO_URLS: https://github.com/lsst-sqre/system-test,https://github.com/rubin-dp0/tutorial-notebooks
      AUTO_REPO_BRANCH: prod
      AUTO_REPO_SPECS: https://github.com/lsst-sqre/system-test@prod,https://github.com/rubin-dp0/tutorial-notebooks@prod
    volumes:
      - name: home
        nfs:
          path: /share1/home
          server: 10.87.86.26
      - name: project
        nfs:
          path: /share1/project
          server: 10.87.86.26
      - name: scratch
        nfs:
          path: /share1/scratch
          server: 10.87.86.26
    volume_mounts:
      - name: home
        mountPath: /home
      - name: project
        mountPath: /project
      - name: scratch
        mountPath: /scratch

  vault_secret_path: "secret/k8s_operator/data-dev.lsst.cloud/nublado2"

pull-secret:
  enabled: true
  path: "secret/k8s_operator/data-dev.lsst.cloud/pull-secret"
