apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: sasquatch
  namespace: sasquatch
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/sasquatch"
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: ts-salkafka
  namespace: sasquatch
spec:
  keys:
    - ts-salkafka-password
  path: "{{ .Values.global.vaultSecretsPath }}/sasquatch"
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/pull-secret"
  type: kubernetes.io/dockerconfigjson
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: tls-certs
  namespace: sasquatch
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/efd/tls-certs"
  type: Opaque
