apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: sasquatch
  namespace: sasquatch
spec:
  path: {{ .Values.vaultSecretsPath }}/sasquatch
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: ts-salkafka
  namespace: sasquatch
spec:
  keys:
    - ts-salkafka-password
  path: {{ .Values.vaultSecretsPath }}/sasquatch
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
spec:
  path: {{ .Values.vaultSecretsPath }}/pull-secret
  type: kubernetes.io/dockerconfigjson
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: sasquatch-nexus3-docker
  namespace: sasquatch
spec:
  path: {{ .Values.vaultSecretsPath }}/pull-secret
  type: kubernetes.io/dockerconfigjson
