apiVersion: v2
name: datalinker
version: 1.0.0
dependencies:
  - name: datalinker
    version: 0.1.6
    repository: https://lsst-sqre.github.io/charts/
  - name: pull-secret
    version: 0.1.2
    repository: https://lsst-sqre.github.io/charts/
