apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: postgres
  namespace: exposurelog
spec:
  path: "{{- .Values.global.vaultSecretsPath }}/postgres"
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
  labels:
    {{- include "exposurelog.labels" . | nindent 4 }}
spec:
  path: "{{- .Values.global.vaultSecretsPath }}/pull-secret"
  type: kubernetes.io/dockerconfigjson
