apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "noteburst.fullname" . }}-worker
  labels:
    {{- include "noteburst.labels" . | nindent 4 }}
data:
  SAFIR_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  NOTEBURST_ENVIRONMENT_URL: {{ .Values.global.baseUrl | quote }}
  NOTEBURST_REDIS_URL: "redis://{{ include "noteburst.fullname" . }}-redis-master.{{ .Release.Namespace }}:{{ .Values.redis.master.service.ports.redis }}/0"
  NOTEBURST_WORKER_LOCK_REDIS_URL: "redis://{{ include "noteburst.fullname" . }}-redis-master.{{ .Release.Namespace }}:{{ .Values.redis.master.service.ports.redis }}/1"
