# Default values for times-square.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  # -- Number of API deployment pods to start
  api: 1

  # -- Number of worker deployment pods to start
  worker: 1

image:
  # -- Image to use in the times-square deployment
  repository: ghcr.io/lsst-sqre/times-square

  # -- Pull policy for the times-square image
  pullPolicy: IfNotPresent

  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Secret names to use for all Docker pulls
imagePullSecrets: []

# -- Override the base name for resources
nameOverride: ""

# -- Override the full name for resources (includes the release name)
fullnameOverride: ""

# -- Annotations for the times-square deployment pod
podAnnotations: {}

serviceAccount:
  # -- Force creation of a service account. Normally, no service account is
  # used or mounted. If CloudSQL is enabled, a service account is always
  # created regardless of this value.
  create: false

  # -- Annotations to add to the service account. If CloudSQL is in use, the
  # annotation specifying the Google service account will also be added.
  annotations: {}

  # -- Name of the service account to use
  # @default -- Name based on the fullname template
  name: ""

service:
  # -- Type of service to create
  type: ClusterIP

  # -- Port of the service to create and map to the ingress
  port: 8080

ingress:
  # -- Create an ingress resource
  enabled: true

  # -- Gafaelfawr auth query string
  gafaelfawrAuthQuery: "scope=exec:admin&auth_type=basic"

  # -- Additional annotations for the ingress rule
  annotations: {}

  # -- Path type for the ingress rule
  pathType: ImplementationSpecific

  # -- URL path to dispatch to the times-square deployment pod
  path: "/times-square/api"

# -- Resource limits and requests for the times-square deployment pod
resources: {}

autoscaling:
  # -- Enable autoscaling of times-square deployment
  enabled: false

  # -- Minimum number of times-square deployment pods
  minReplicas: 1

  # -- Maximum number of times-square deployment pods
  maxReplicas: 100

  # -- Target CPU utilization of times-square deployment pods
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Node selection rules for the times-square deployment pod
nodeSelector: {}

# -- Tolerations for the times-square deployment pod
tolerations: []

# -- Affinity rules for the times-square deployment pod
affinity: {}

# -- Path to the Vault secret (`secret/k8s_operator/<host>/times-square`, for
# example)
# @default -- None, must be set
vaultSecretsPath: ""

# Configurations for the times-square application.
config:
  # -- Name of the service.
  name: "times-square"

  # -- Run profile: "production" or "development"
  profile: "production"

  # -- Logging level: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
  logLevel: "INFO"

  # -- URL for the PostgreSQL database
  # @default -- None, must be set
  databaseUrl: ""

  # -- URL for Redis html / noteburst job cache database
  # @default -- None, must be set
  redisCacheUrl: ""

  # -- URL for Redis arq queue database
  # @default -- None, must be set
  queueRedisUrl: ""

  # -- GitHub application ID
  githubAppId: ""

  # -- Toggle to enable the GitHub App functionality
  enableGitHubApp: "False"

cloudsql:
  # -- Enable the Cloud SQL Auth Proxy sidecar, used with CloudSQL databases
  # on Google Cloud
  enabled: false

  image:
    # -- Cloud SQL Auth Proxy image to use
    repository: "gcr.io/cloudsql-docker/gce-proxy"

    # -- Cloud SQL Auth Proxy tag to use
    tag: "1.30.0"

    # -- Pull policy for Cloud SQL Auth Proxy images
    pullPolicy: "IfNotPresent"

  # -- Instance connection name for a CloudSQL PostgreSQL instance
  instanceConnectionName: ""

  # -- The Google service account that has an IAM binding to the `times-square`
  # Kubernetes service accounts and has the `cloudsql.client` role
  serviceAccount: ""

redis:
  auth:
    enabled: false
